apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.appName }}
spec:
  template:
    spec:
      containers:
      - name: "{{ .Values.appName }}-schema-job"
        image: "public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load"
        
      restartPolicy: Never
  backoffLimit: 4
